# Stage: stage2_ingestion
# Consumes formal objects: public_chain, clock_chain_profile, notice_version_chain, fixation_bundle
# Dependent handoff: H-01-STAGE1-TO-STAGE2, H-02-STAGE2-TO-STAGE3
# Dependent schema/contracts: handoff/stage_handoff_catalog.json, contracts/schemas/schema_catalog.json, contracts/enums/enum_catalog.json

from stage2_ingestion.public_source_adapters import (
    LOCAL_PUBLIC_RESOURCE_TRADING_CENTER_ADAPTER_ID,
    LocalPublicResourceTradingCenterSourceAdapter,
    PROVINCIAL_BIDDING_PLATFORM_ADAPTER_ID,
    PROVINCIAL_BIDDING_PLATFORM_SOURCE_FAMILY,
    PublicSourceAdapterConfig,
    PublicSourceBoundaryError,
    PublicSourceSnapshotRequest,
    PublicSourceSnapshotResult,
    PublicSourceTimeoutError,
    PublicSourceTransportError,
    PublicSourceTransportResponse,
    StaticPublicSourceTransport,
    provincial_bidding_platform_adapter_config,
    resolve_public_source_adapter_config,
)
from stage2_ingestion.real_public_url_fetcher import (
    NATIONAL_VERIFICATION_ENTRY_PROFILE_IDS,
    PUBLIC_ATTACHMENT_PROFILE_IDS,
    REAL_PUBLIC_ATTACHMENT_FETCH_MODE,
    REAL_PUBLIC_ATTACHMENT_PROFILES,
    REAL_PUBLIC_ATTACHMENT_SNAPSHOT_KIND,
    REPRESENTATIVE_LOCAL_PLATFORM_ENTRY_PROFILE_IDS,
    REAL_PUBLIC_ENTRY_FETCH_MODE,
    REAL_PUBLIC_ENTRY_FETCHER_ID,
    REAL_PUBLIC_ENTRY_PROFILES,
    RealPublicAttachmentProfile,
    RealPublicEntryFetcher,
    RealPublicEntryProfile,
    RealPublicFetchResponse,
    RealPublicUrlBoundaryError,
    UrlLibRealPublicFetchTransport,
)
from stage2_ingestion.source_validation import (
    SOURCE_VALIDATION_SAMPLE_MATRIX,
    PublicSourceValidationResult,
    PublicSourceValidationSample,
    build_blocked_validation_result,
    build_degraded_validation_result,
    build_source_coverage_report,
    build_supported_validation_result,
    build_validation_request,
    source_validation_samples,
)

__all__ = [
    "LOCAL_PUBLIC_RESOURCE_TRADING_CENTER_ADAPTER_ID",
    "LocalPublicResourceTradingCenterSourceAdapter",
    "PROVINCIAL_BIDDING_PLATFORM_ADAPTER_ID",
    "PROVINCIAL_BIDDING_PLATFORM_SOURCE_FAMILY",
    "PublicSourceAdapterConfig",
    "PublicSourceBoundaryError",
    "PublicSourceSnapshotRequest",
    "PublicSourceSnapshotResult",
    "PublicSourceTimeoutError",
    "PublicSourceTransportError",
    "PublicSourceTransportResponse",
    "StaticPublicSourceTransport",
    "SOURCE_VALIDATION_SAMPLE_MATRIX",
    "PublicSourceValidationResult",
    "PublicSourceValidationSample",
    "NATIONAL_VERIFICATION_ENTRY_PROFILE_IDS",
    "PUBLIC_ATTACHMENT_PROFILE_IDS",
    "REAL_PUBLIC_ATTACHMENT_FETCH_MODE",
    "REAL_PUBLIC_ATTACHMENT_PROFILES",
    "REAL_PUBLIC_ATTACHMENT_SNAPSHOT_KIND",
    "REPRESENTATIVE_LOCAL_PLATFORM_ENTRY_PROFILE_IDS",
    "REAL_PUBLIC_ENTRY_FETCH_MODE",
    "REAL_PUBLIC_ENTRY_FETCHER_ID",
    "REAL_PUBLIC_ENTRY_PROFILES",
    "RealPublicAttachmentProfile",
    "RealPublicEntryFetcher",
    "RealPublicEntryProfile",
    "RealPublicFetchResponse",
    "RealPublicUrlBoundaryError",
    "build_blocked_validation_result",
    "build_degraded_validation_result",
    "build_source_coverage_report",
    "build_supported_validation_result",
    "build_validation_request",
    "provincial_bidding_platform_adapter_config",
    "resolve_public_source_adapter_config",
    "source_validation_samples",
    "UrlLibRealPublicFetchTransport",
]
